"""empty message

Revision ID: 055f3ababcea
Revises: 
Create Date: 2023-10-21 12:21:17.511484

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '055f3ababcea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('my_list', schema=None) as batch_op:
        batch_op.drop_column('profile_id')

    with op.batch_alter_table('now_watching', schema=None) as batch_op:
        batch_op.drop_column('profile_id')

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ratings', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('myList', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('nowWatching', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'ratings', ['ratings'], ['id'])
        batch_op.create_foreign_key(None, 'now_watching', ['nowWatching'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['uuid'])
        batch_op.create_foreign_key(None, 'my_list', ['myList'], ['id'])

    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_column('profile_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profiles', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'profiles', ['profiles'], ['id'])
        batch_op.drop_column('plan')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan', mysql.VARCHAR(length=32), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('profiles')

    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_id', mysql.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('nowWatching')
        batch_op.drop_column('myList')
        batch_op.drop_column('ratings')

    with op.batch_alter_table('now_watching', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_id', mysql.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('my_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_id', mysql.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
