"""empty message

Revision ID: c4c76498f6c1
Revises: 012959aa8c48
Create Date: 2023-10-21 12:51:31.107532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4c76498f6c1'
down_revision = '012959aa8c48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('my_list', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'profiles', ['profile_id'], ['id'])

    with op.batch_alter_table('now_watching', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'profiles', ['profile_id'], ['id'])

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['uuid'])

    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'profiles', ['profile_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'plans', ['plan'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('now_watching', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('my_list', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
