"""empty message

Revision ID: dc35376fa562
Revises: 8fa10e1d0f35
Create Date: 2023-10-21 12:35:08.021837

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dc35376fa562'
down_revision = '8fa10e1d0f35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_constraint('profiles_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('profiles_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('profiles_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['uuid'])
        batch_op.drop_column('ratings')
        batch_op.drop_column('myList')
        batch_op.drop_column('nowWatching')

    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'profiles', ['profile_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('plan')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan', mysql.VARCHAR(length=32), nullable=True))

    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nowWatching', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('myList', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ratings', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('profiles_ibfk_2', 'now_watching', ['nowWatching'], ['id'])
        batch_op.create_foreign_key('profiles_ibfk_3', 'my_list', ['myList'], ['id'])
        batch_op.create_foreign_key('profiles_ibfk_1', 'ratings', ['ratings'], ['id'])

    # ### end Alembic commands ###
